### ISSUE TITLE
Yuzu Game Cover Not Appearing In Deck Mode

### ISSUE THREAD

**Issue by titan-91** [ruanformigoni/agape#2]
When using my-game-cover.png, the agape install script successfully finds and generates the cover file but the Steam Deck's deck mode does not show the cover. The PNG file I'm using is 603x993 and 1,037,664 bytes. Does it need to be a smaller file?

**Comment by ruanformigoni** [comment]
No, the size shouldn't cause any issue. You mean in the file manager? After following the instructions [here](https://github.com/ruanformigoni/agape#tutorial-on-how-to-show-icons-for-generated-appimages), you should view the file with the thunar file manager to generate the icon, after that it should appear everywhere.

**Comment by titan-91** [comment]
Oh I see, I must have overlooked that. I will close this issue. Thank you!
